# Generated by Django 5.0.1 on 2024-07-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='payment',
            field=models.CharField(default='unique', max_length=40),
        ),
    ]
