# Generated by Django 5.0.1 on 2024-07-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_product_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='payment',
            field=models.CharField(max_length=40),
        ),
    ]
