# Generated by Django 5.0.1 on 2024-07-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_alter_product_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='questions',
            field=models.TextField(default='n'),
        ),
    ]
