# Generated by Django 5.0.1 on 2024-07-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_product_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='questions',
            field=models.TextField(),
        ),
    ]
