# Generated by Django 5.0.1 on 2024-07-30 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_remove_product_questions_faq'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMe',
        ),
    ]
